version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_job_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
    restart: always
    networks:
      - distributed_job_network

  db:
    image: mysql:8.0
    container_name: distributed_job_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=distributed_job
      - TZ=Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - distributed_job_network

networks:
  distributed_job_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local