global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "distributed_job_api"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "distributed_job_scheduler"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "distributed_job_worker"
    static_configs:
      - targets: ["host.docker.internal:8082"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
