server:
  host: 0.0.0.0
  port: 8080
  context_path: /v1
  shutdown_timeout: 30

database:
  url: localhost:3306
  username: root
  password: root
  schema: distributed_job
  max_idle: 10
  max_conn: 50

redis:
  url: localhost:6379
  password: ""
  db: 0
  max_idle: 10
  max_active: 100
  idle_timeout: 300
  connect_timeout: 5

log:
  level: info
  filename: logs/distributed_job.log
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

auth:
  jwt_secret: 8d7e48a2dc1d3e7f9a8b6c5d4e3f2a1b
  jwt_refresh_secret: 9s8d7f6g5h4j3k2l1q0w9e8r7t6y5u4i
  jwt_expire_minutes: 30
  jwt_refresh_expire_days: 7
  enable_encryption: true
  token_revocation_strategy: redis # options: memory, redis

job:
  http_workers: 10
  grpc_workers: 10
  queue_size: 100
  max_retry: 3
  retry_backoff: 5

rpc:
  port: 8081
  max_concurrent_streams: 1000
  keep_alive_time: 60
  keep_alive_timeout: 20
